#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_BLL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLYRAPCHIEUPHIM")]
	public partial class QUANLYRAPCHIEUPHIMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBinhLuan(BinhLuan instance);
    partial void UpdateBinhLuan(BinhLuan instance);
    partial void DeleteBinhLuan(BinhLuan instance);
    partial void InsertVe(Ve instance);
    partial void UpdateVe(Ve instance);
    partial void DeleteVe(Ve instance);
    partial void InsertCaChieu(CaChieu instance);
    partial void UpdateCaChieu(CaChieu instance);
    partial void DeleteCaChieu(CaChieu instance);
    partial void InsertDatVe(DatVe instance);
    partial void UpdateDatVe(DatVe instance);
    partial void DeleteDatVe(DatVe instance);
    partial void InsertGhe(Ghe instance);
    partial void UpdateGhe(Ghe instance);
    partial void DeleteGhe(Ghe instance);
    partial void InsertLichChieu(LichChieu instance);
    partial void UpdateLichChieu(LichChieu instance);
    partial void DeleteLichChieu(LichChieu instance);
    partial void InsertLoaiGhe(LoaiGhe instance);
    partial void UpdateLoaiGhe(LoaiGhe instance);
    partial void DeleteLoaiGhe(LoaiGhe instance);
    partial void InsertLoaiPhim(LoaiPhim instance);
    partial void UpdateLoaiPhim(LoaiPhim instance);
    partial void DeleteLoaiPhim(LoaiPhim instance);
    partial void InsertPhim(Phim instance);
    partial void UpdatePhim(Phim instance);
    partial void DeletePhim(Phim instance);
    partial void InsertPhong(Phong instance);
    partial void UpdatePhong(Phong instance);
    partial void DeletePhong(Phong instance);
    partial void InsertSuatchieu(Suatchieu instance);
    partial void UpdateSuatchieu(Suatchieu instance);
    partial void DeleteSuatchieu(Suatchieu instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertThongTin(ThongTin instance);
    partial void UpdateThongTin(ThongTin instance);
    partial void DeleteThongTin(ThongTin instance);
    partial void InsertQuyen(Quyen instance);
    partial void UpdateQuyen(Quyen instance);
    partial void DeleteQuyen(Quyen instance);
    #endregion
		
		public QUANLYRAPCHIEUPHIMDataContext() : 
				base(global::DAL_BLL.Properties.Settings.Default.QUANLYRAPCHIEUPHIMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QUANLYRAPCHIEUPHIMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QUANLYRAPCHIEUPHIMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QUANLYRAPCHIEUPHIMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QUANLYRAPCHIEUPHIMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BinhLuan> BinhLuans
		{
			get
			{
				return this.GetTable<BinhLuan>();
			}
		}
		
		public System.Data.Linq.Table<Ve> Ves
		{
			get
			{
				return this.GetTable<Ve>();
			}
		}
		
		public System.Data.Linq.Table<CaChieu> CaChieus
		{
			get
			{
				return this.GetTable<CaChieu>();
			}
		}
		
		public System.Data.Linq.Table<DatVe> DatVes
		{
			get
			{
				return this.GetTable<DatVe>();
			}
		}
		
		public System.Data.Linq.Table<Ghe> Ghes
		{
			get
			{
				return this.GetTable<Ghe>();
			}
		}
		
		public System.Data.Linq.Table<LichChieu> LichChieus
		{
			get
			{
				return this.GetTable<LichChieu>();
			}
		}
		
		public System.Data.Linq.Table<LoaiGhe> LoaiGhes
		{
			get
			{
				return this.GetTable<LoaiGhe>();
			}
		}
		
		public System.Data.Linq.Table<LoaiPhim> LoaiPhims
		{
			get
			{
				return this.GetTable<LoaiPhim>();
			}
		}
		
		public System.Data.Linq.Table<Phim> Phims
		{
			get
			{
				return this.GetTable<Phim>();
			}
		}
		
		public System.Data.Linq.Table<Phong> Phongs
		{
			get
			{
				return this.GetTable<Phong>();
			}
		}
		
		public System.Data.Linq.Table<Suatchieu> Suatchieus
		{
			get
			{
				return this.GetTable<Suatchieu>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<ThongTin> ThongTins
		{
			get
			{
				return this.GetTable<ThongTin>();
			}
		}
		
		public System.Data.Linq.Table<Quyen> Quyens
		{
			get
			{
				return this.GetTable<Quyen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BinhLuan")]
	public partial class BinhLuan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdPhim;
		
		private System.Nullable<int> _IdTK;
		
		private string _NoiDung;
		
		private System.DateTime _NgayDang;
		
		private bool _TinhTrang;
		
		private int _DanhGia;
		
		private EntityRef<Phim> _Phim;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdPhimChanging(System.Nullable<int> value);
    partial void OnIdPhimChanged();
    partial void OnIdTKChanging(System.Nullable<int> value);
    partial void OnIdTKChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNgayDangChanging(System.DateTime value);
    partial void OnNgayDangChanged();
    partial void OnTinhTrangChanging(bool value);
    partial void OnTinhTrangChanged();
    partial void OnDanhGiaChanging(int value);
    partial void OnDanhGiaChanged();
    #endregion
		
		public BinhLuan()
		{
			this._Phim = default(EntityRef<Phim>);
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhim", DbType="Int")]
		public System.Nullable<int> IdPhim
		{
			get
			{
				return this._IdPhim;
			}
			set
			{
				if ((this._IdPhim != value))
				{
					if (this._Phim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPhimChanging(value);
					this.SendPropertyChanging();
					this._IdPhim = value;
					this.SendPropertyChanged("IdPhim");
					this.OnIdPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTK", DbType="Int")]
		public System.Nullable<int> IdTK
		{
			get
			{
				return this._IdTK;
			}
			set
			{
				if ((this._IdTK != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTKChanging(value);
					this.SendPropertyChanging();
					this._IdTK = value;
					this.SendPropertyChanged("IdTK");
					this.OnIdTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="Date NOT NULL")]
		public System.DateTime NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit NOT NULL")]
		public bool TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhGia", DbType="Int NOT NULL")]
		public int DanhGia
		{
			get
			{
				return this._DanhGia;
			}
			set
			{
				if ((this._DanhGia != value))
				{
					this.OnDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._DanhGia = value;
					this.SendPropertyChanged("DanhGia");
					this.OnDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_BinhLuan", Storage="_Phim", ThisKey="IdPhim", OtherKey="Id", IsForeignKey=true)]
		public Phim Phim
		{
			get
			{
				return this._Phim.Entity;
			}
			set
			{
				Phim previousValue = this._Phim.Entity;
				if (((previousValue != value) 
							|| (this._Phim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phim.Entity = null;
						previousValue.BinhLuans.Remove(this);
					}
					this._Phim.Entity = value;
					if ((value != null))
					{
						value.BinhLuans.Add(this);
						this._IdPhim = value.Id;
					}
					else
					{
						this._IdPhim = default(Nullable<int>);
					}
					this.SendPropertyChanged("Phim");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_BinhLuan", Storage="_TaiKhoan", ThisKey="IdTK", OtherKey="Id", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.BinhLuans.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.BinhLuans.Add(this);
						this._IdTK = value.Id;
					}
					else
					{
						this._IdTK = default(Nullable<int>);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ve")]
	public partial class Ve : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdTaiKhoan;
		
		private System.Nullable<int> _IdPhim;
		
		private System.Nullable<int> _IdGhe;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private System.Nullable<decimal> _GiaVe;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<int> _TinhTrang;
		
		private System.Nullable<int> _IdLC;
		
		private System.Nullable<int> _IdKM;
		
		private EntityRef<Ghe> _Ghe;
		
		private EntityRef<LichChieu> _LichChieu;
		
		private EntityRef<Phim> _Phim;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdTaiKhoanChanging(System.Nullable<int> value);
    partial void OnIdTaiKhoanChanged();
    partial void OnIdPhimChanging(System.Nullable<int> value);
    partial void OnIdPhimChanged();
    partial void OnIdGheChanging(System.Nullable<int> value);
    partial void OnIdGheChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    partial void OnGiaVeChanging(System.Nullable<decimal> value);
    partial void OnGiaVeChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnTinhTrangChanging(System.Nullable<int> value);
    partial void OnTinhTrangChanged();
    partial void OnIdLCChanging(System.Nullable<int> value);
    partial void OnIdLCChanged();
    partial void OnIdKMChanging(System.Nullable<int> value);
    partial void OnIdKMChanged();
    #endregion
		
		public Ve()
		{
			this._Ghe = default(EntityRef<Ghe>);
			this._LichChieu = default(EntityRef<LichChieu>);
			this._Phim = default(EntityRef<Phim>);
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTaiKhoan", DbType="Int")]
		public System.Nullable<int> IdTaiKhoan
		{
			get
			{
				return this._IdTaiKhoan;
			}
			set
			{
				if ((this._IdTaiKhoan != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IdTaiKhoan = value;
					this.SendPropertyChanged("IdTaiKhoan");
					this.OnIdTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhim", DbType="Int")]
		public System.Nullable<int> IdPhim
		{
			get
			{
				return this._IdPhim;
			}
			set
			{
				if ((this._IdPhim != value))
				{
					if (this._Phim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPhimChanging(value);
					this.SendPropertyChanging();
					this._IdPhim = value;
					this.SendPropertyChanged("IdPhim");
					this.OnIdPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGhe", DbType="Int")]
		public System.Nullable<int> IdGhe
		{
			get
			{
				return this._IdGhe;
			}
			set
			{
				if ((this._IdGhe != value))
				{
					if (this._Ghe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdGheChanging(value);
					this.SendPropertyChanging();
					this._IdGhe = value;
					this.SendPropertyChanged("IdGhe");
					this.OnIdGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaVe", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GiaVe
		{
			get
			{
				return this._GiaVe;
			}
			set
			{
				if ((this._GiaVe != value))
				{
					this.OnGiaVeChanging(value);
					this.SendPropertyChanging();
					this._GiaVe = value;
					this.SendPropertyChanged("GiaVe");
					this.OnGiaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLC", DbType="Int")]
		public System.Nullable<int> IdLC
		{
			get
			{
				return this._IdLC;
			}
			set
			{
				if ((this._IdLC != value))
				{
					if (this._LichChieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdLCChanging(value);
					this.SendPropertyChanging();
					this._IdLC = value;
					this.SendPropertyChanged("IdLC");
					this.OnIdLCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKM", DbType="Int")]
		public System.Nullable<int> IdKM
		{
			get
			{
				return this._IdKM;
			}
			set
			{
				if ((this._IdKM != value))
				{
					this.OnIdKMChanging(value);
					this.SendPropertyChanging();
					this._IdKM = value;
					this.SendPropertyChanged("IdKM");
					this.OnIdKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ghe_Ve", Storage="_Ghe", ThisKey="IdGhe", OtherKey="ghe_id", IsForeignKey=true)]
		public Ghe Ghe
		{
			get
			{
				return this._Ghe.Entity;
			}
			set
			{
				Ghe previousValue = this._Ghe.Entity;
				if (((previousValue != value) 
							|| (this._Ghe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ghe.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._Ghe.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._IdGhe = value.ghe_id;
					}
					else
					{
						this._IdGhe = default(Nullable<int>);
					}
					this.SendPropertyChanged("Ghe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichChieu_Ve", Storage="_LichChieu", ThisKey="IdLC", OtherKey="Id", IsForeignKey=true)]
		public LichChieu LichChieu
		{
			get
			{
				return this._LichChieu.Entity;
			}
			set
			{
				LichChieu previousValue = this._LichChieu.Entity;
				if (((previousValue != value) 
							|| (this._LichChieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LichChieu.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._LichChieu.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._IdLC = value.Id;
					}
					else
					{
						this._IdLC = default(Nullable<int>);
					}
					this.SendPropertyChanged("LichChieu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_Ve", Storage="_Phim", ThisKey="IdPhim", OtherKey="Id", IsForeignKey=true)]
		public Phim Phim
		{
			get
			{
				return this._Phim.Entity;
			}
			set
			{
				Phim previousValue = this._Phim.Entity;
				if (((previousValue != value) 
							|| (this._Phim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phim.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._Phim.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._IdPhim = value.Id;
					}
					else
					{
						this._IdPhim = default(Nullable<int>);
					}
					this.SendPropertyChanged("Phim");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_Ve", Storage="_TaiKhoan", ThisKey="IdTaiKhoan", OtherKey="Id", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._IdTaiKhoan = value.Id;
					}
					else
					{
						this._IdTaiKhoan = default(Nullable<int>);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CaChieu")]
	public partial class CaChieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCC;
		
		private string _TenCC;
		
		private EntitySet<LichChieu> _LichChieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCCChanging(int value);
    partial void OnIdCCChanged();
    partial void OnTenCCChanging(string value);
    partial void OnTenCCChanged();
    #endregion
		
		public CaChieu()
		{
			this._LichChieus = new EntitySet<LichChieu>(new Action<LichChieu>(this.attach_LichChieus), new Action<LichChieu>(this.detach_LichChieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCC
		{
			get
			{
				return this._IdCC;
			}
			set
			{
				if ((this._IdCC != value))
				{
					this.OnIdCCChanging(value);
					this.SendPropertyChanging();
					this._IdCC = value;
					this.SendPropertyChanged("IdCC");
					this.OnIdCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenCC
		{
			get
			{
				return this._TenCC;
			}
			set
			{
				if ((this._TenCC != value))
				{
					this.OnTenCCChanging(value);
					this.SendPropertyChanging();
					this._TenCC = value;
					this.SendPropertyChanged("TenCC");
					this.OnTenCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CaChieu_LichChieu", Storage="_LichChieus", ThisKey="IdCC", OtherKey="IdCC")]
		public EntitySet<LichChieu> LichChieus
		{
			get
			{
				return this._LichChieus;
			}
			set
			{
				this._LichChieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.CaChieu = this;
		}
		
		private void detach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.CaChieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DatVe")]
	public partial class DatVe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDatVe;
		
		private int _IDTK;
		
		private string _IDve;
		
		private System.DateTime _NgayDat;
		
		private System.Nullable<decimal> _TongTien;
		
		private string _SDT;
		
		private string _Email;
		
		private string _HoTen;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDatVeChanging(int value);
    partial void OnIDDatVeChanged();
    partial void OnIDTKChanging(int value);
    partial void OnIDTKChanged();
    partial void OnIDveChanging(string value);
    partial void OnIDveChanged();
    partial void OnNgayDatChanging(System.DateTime value);
    partial void OnNgayDatChanged();
    partial void OnTongTienChanging(System.Nullable<decimal> value);
    partial void OnTongTienChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    #endregion
		
		public DatVe()
		{
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDatVe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDDatVe
		{
			get
			{
				return this._IDDatVe;
			}
			set
			{
				if ((this._IDDatVe != value))
				{
					this.OnIDDatVeChanging(value);
					this.SendPropertyChanging();
					this._IDDatVe = value;
					this.SendPropertyChanged("IDDatVe");
					this.OnIDDatVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTK", DbType="Int NOT NULL")]
		public int IDTK
		{
			get
			{
				return this._IDTK;
			}
			set
			{
				if ((this._IDTK != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTKChanging(value);
					this.SendPropertyChanging();
					this._IDTK = value;
					this.SendPropertyChanged("IDTK");
					this.OnIDTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDve", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string IDve
		{
			get
			{
				return this._IDve;
			}
			set
			{
				if ((this._IDve != value))
				{
					this.OnIDveChanging(value);
					this.SendPropertyChanging();
					this._IDve = value;
					this.SendPropertyChanged("IDve");
					this.OnIDveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="DateTime NOT NULL")]
		public System.DateTime NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Money")]
		public System.Nullable<decimal> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(200)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(200)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_DatVe", Storage="_TaiKhoan", ThisKey="IDTK", OtherKey="Id", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.DatVes.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.DatVes.Add(this);
						this._IDTK = value.Id;
					}
					else
					{
						this._IDTK = default(int);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ghe")]
	public partial class Ghe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ghe_id;
		
		private System.Nullable<int> _Loai_id;
		
		private bool _TringTrang;
		
		private System.Nullable<int> _Id_phong;
		
		private string _TenGhe;
		
		private string _HangGhe;
		
		private EntitySet<Ve> _Ves;
		
		private EntityRef<LoaiGhe> _LoaiGhe;
		
		private EntityRef<Phong> _Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onghe_idChanging(int value);
    partial void Onghe_idChanged();
    partial void OnLoai_idChanging(System.Nullable<int> value);
    partial void OnLoai_idChanged();
    partial void OnTringTrangChanging(bool value);
    partial void OnTringTrangChanged();
    partial void OnId_phongChanging(System.Nullable<int> value);
    partial void OnId_phongChanged();
    partial void OnTenGheChanging(string value);
    partial void OnTenGheChanged();
    partial void OnHangGheChanging(string value);
    partial void OnHangGheChanged();
    #endregion
		
		public Ghe()
		{
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			this._LoaiGhe = default(EntityRef<LoaiGhe>);
			this._Phong = default(EntityRef<Phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghe_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ghe_id
		{
			get
			{
				return this._ghe_id;
			}
			set
			{
				if ((this._ghe_id != value))
				{
					this.Onghe_idChanging(value);
					this.SendPropertyChanging();
					this._ghe_id = value;
					this.SendPropertyChanged("ghe_id");
					this.Onghe_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai_id", DbType="Int")]
		public System.Nullable<int> Loai_id
		{
			get
			{
				return this._Loai_id;
			}
			set
			{
				if ((this._Loai_id != value))
				{
					if (this._LoaiGhe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoai_idChanging(value);
					this.SendPropertyChanging();
					this._Loai_id = value;
					this.SendPropertyChanged("Loai_id");
					this.OnLoai_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TringTrang", DbType="Bit NOT NULL")]
		public bool TringTrang
		{
			get
			{
				return this._TringTrang;
			}
			set
			{
				if ((this._TringTrang != value))
				{
					this.OnTringTrangChanging(value);
					this.SendPropertyChanging();
					this._TringTrang = value;
					this.SendPropertyChanged("TringTrang");
					this.OnTringTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_phong", DbType="Int")]
		public System.Nullable<int> Id_phong
		{
			get
			{
				return this._Id_phong;
			}
			set
			{
				if ((this._Id_phong != value))
				{
					if (this._Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_phongChanging(value);
					this.SendPropertyChanging();
					this._Id_phong = value;
					this.SendPropertyChanged("Id_phong");
					this.OnId_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGhe", DbType="VarChar(50)")]
		public string TenGhe
		{
			get
			{
				return this._TenGhe;
			}
			set
			{
				if ((this._TenGhe != value))
				{
					this.OnTenGheChanging(value);
					this.SendPropertyChanging();
					this._TenGhe = value;
					this.SendPropertyChanged("TenGhe");
					this.OnTenGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HangGhe", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string HangGhe
		{
			get
			{
				return this._HangGhe;
			}
			set
			{
				if ((this._HangGhe != value))
				{
					this.OnHangGheChanging(value);
					this.SendPropertyChanging();
					this._HangGhe = value;
					this.SendPropertyChanged("HangGhe");
					this.OnHangGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ghe_Ve", Storage="_Ves", ThisKey="ghe_id", OtherKey="IdGhe")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiGhe_Ghe", Storage="_LoaiGhe", ThisKey="Loai_id", OtherKey="Id", IsForeignKey=true)]
		public LoaiGhe LoaiGhe
		{
			get
			{
				return this._LoaiGhe.Entity;
			}
			set
			{
				LoaiGhe previousValue = this._LoaiGhe.Entity;
				if (((previousValue != value) 
							|| (this._LoaiGhe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiGhe.Entity = null;
						previousValue.Ghes.Remove(this);
					}
					this._LoaiGhe.Entity = value;
					if ((value != null))
					{
						value.Ghes.Add(this);
						this._Loai_id = value.Id;
					}
					else
					{
						this._Loai_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiGhe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_Ghe", Storage="_Phong", ThisKey="Id_phong", OtherKey="Id", IsForeignKey=true)]
		public Phong Phong
		{
			get
			{
				return this._Phong.Entity;
			}
			set
			{
				Phong previousValue = this._Phong.Entity;
				if (((previousValue != value) 
							|| (this._Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phong.Entity = null;
						previousValue.Ghes.Remove(this);
					}
					this._Phong.Entity = value;
					if ((value != null))
					{
						value.Ghes.Add(this);
						this._Id_phong = value.Id;
					}
					else
					{
						this._Id_phong = default(Nullable<int>);
					}
					this.SendPropertyChanged("Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.Ghe = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.Ghe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichChieu")]
	public partial class LichChieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _NgayChieu;
		
		private string _Thu;
		
		private System.Nullable<decimal> _Phuthulc;
		
		private System.Nullable<int> _IdPhim;
		
		private System.Nullable<int> _IdCC;
		
		private System.Nullable<int> _IdSC;
		
		private System.Nullable<System.TimeSpan> _GioBD;
		
		private System.Nullable<System.TimeSpan> _GioKT;
		
		private System.Nullable<int> _IdPhong;
		
		private EntitySet<Ve> _Ves;
		
		private EntityRef<CaChieu> _CaChieu;
		
		private EntityRef<Phim> _Phim;
		
		private EntityRef<Phong> _Phong;
		
		private EntityRef<Suatchieu> _Suatchieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNgayChieuChanging(System.DateTime value);
    partial void OnNgayChieuChanged();
    partial void OnThuChanging(string value);
    partial void OnThuChanged();
    partial void OnPhuthulcChanging(System.Nullable<decimal> value);
    partial void OnPhuthulcChanged();
    partial void OnIdPhimChanging(System.Nullable<int> value);
    partial void OnIdPhimChanged();
    partial void OnIdCCChanging(System.Nullable<int> value);
    partial void OnIdCCChanged();
    partial void OnIdSCChanging(System.Nullable<int> value);
    partial void OnIdSCChanged();
    partial void OnGioBDChanging(System.Nullable<System.TimeSpan> value);
    partial void OnGioBDChanged();
    partial void OnGioKTChanging(System.Nullable<System.TimeSpan> value);
    partial void OnGioKTChanged();
    partial void OnIdPhongChanging(System.Nullable<int> value);
    partial void OnIdPhongChanged();
    #endregion
		
		public LichChieu()
		{
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			this._CaChieu = default(EntityRef<CaChieu>);
			this._Phim = default(EntityRef<Phim>);
			this._Phong = default(EntityRef<Phong>);
			this._Suatchieu = default(EntityRef<Suatchieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChieu", DbType="DateTime NOT NULL")]
		public System.DateTime NgayChieu
		{
			get
			{
				return this._NgayChieu;
			}
			set
			{
				if ((this._NgayChieu != value))
				{
					this.OnNgayChieuChanging(value);
					this.SendPropertyChanging();
					this._NgayChieu = value;
					this.SendPropertyChanged("NgayChieu");
					this.OnNgayChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thu", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Thu
		{
			get
			{
				return this._Thu;
			}
			set
			{
				if ((this._Thu != value))
				{
					this.OnThuChanging(value);
					this.SendPropertyChanging();
					this._Thu = value;
					this.SendPropertyChanged("Thu");
					this.OnThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phuthulc", DbType="Money")]
		public System.Nullable<decimal> Phuthulc
		{
			get
			{
				return this._Phuthulc;
			}
			set
			{
				if ((this._Phuthulc != value))
				{
					this.OnPhuthulcChanging(value);
					this.SendPropertyChanging();
					this._Phuthulc = value;
					this.SendPropertyChanged("Phuthulc");
					this.OnPhuthulcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhim", DbType="Int")]
		public System.Nullable<int> IdPhim
		{
			get
			{
				return this._IdPhim;
			}
			set
			{
				if ((this._IdPhim != value))
				{
					if (this._Phim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPhimChanging(value);
					this.SendPropertyChanging();
					this._IdPhim = value;
					this.SendPropertyChanged("IdPhim");
					this.OnIdPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCC", DbType="Int")]
		public System.Nullable<int> IdCC
		{
			get
			{
				return this._IdCC;
			}
			set
			{
				if ((this._IdCC != value))
				{
					if (this._CaChieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCCChanging(value);
					this.SendPropertyChanging();
					this._IdCC = value;
					this.SendPropertyChanged("IdCC");
					this.OnIdCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSC", DbType="Int")]
		public System.Nullable<int> IdSC
		{
			get
			{
				return this._IdSC;
			}
			set
			{
				if ((this._IdSC != value))
				{
					if (this._Suatchieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdSCChanging(value);
					this.SendPropertyChanging();
					this._IdSC = value;
					this.SendPropertyChanged("IdSC");
					this.OnIdSCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioBD", DbType="Time")]
		public System.Nullable<System.TimeSpan> GioBD
		{
			get
			{
				return this._GioBD;
			}
			set
			{
				if ((this._GioBD != value))
				{
					this.OnGioBDChanging(value);
					this.SendPropertyChanging();
					this._GioBD = value;
					this.SendPropertyChanged("GioBD");
					this.OnGioBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioKT", DbType="Time")]
		public System.Nullable<System.TimeSpan> GioKT
		{
			get
			{
				return this._GioKT;
			}
			set
			{
				if ((this._GioKT != value))
				{
					this.OnGioKTChanging(value);
					this.SendPropertyChanging();
					this._GioKT = value;
					this.SendPropertyChanged("GioKT");
					this.OnGioKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhong", DbType="Int")]
		public System.Nullable<int> IdPhong
		{
			get
			{
				return this._IdPhong;
			}
			set
			{
				if ((this._IdPhong != value))
				{
					if (this._Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPhongChanging(value);
					this.SendPropertyChanging();
					this._IdPhong = value;
					this.SendPropertyChanged("IdPhong");
					this.OnIdPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichChieu_Ve", Storage="_Ves", ThisKey="Id", OtherKey="IdLC")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CaChieu_LichChieu", Storage="_CaChieu", ThisKey="IdCC", OtherKey="IdCC", IsForeignKey=true)]
		public CaChieu CaChieu
		{
			get
			{
				return this._CaChieu.Entity;
			}
			set
			{
				CaChieu previousValue = this._CaChieu.Entity;
				if (((previousValue != value) 
							|| (this._CaChieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CaChieu.Entity = null;
						previousValue.LichChieus.Remove(this);
					}
					this._CaChieu.Entity = value;
					if ((value != null))
					{
						value.LichChieus.Add(this);
						this._IdCC = value.IdCC;
					}
					else
					{
						this._IdCC = default(Nullable<int>);
					}
					this.SendPropertyChanged("CaChieu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_LichChieu", Storage="_Phim", ThisKey="IdPhim", OtherKey="Id", IsForeignKey=true)]
		public Phim Phim
		{
			get
			{
				return this._Phim.Entity;
			}
			set
			{
				Phim previousValue = this._Phim.Entity;
				if (((previousValue != value) 
							|| (this._Phim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phim.Entity = null;
						previousValue.LichChieus.Remove(this);
					}
					this._Phim.Entity = value;
					if ((value != null))
					{
						value.LichChieus.Add(this);
						this._IdPhim = value.Id;
					}
					else
					{
						this._IdPhim = default(Nullable<int>);
					}
					this.SendPropertyChanged("Phim");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_LichChieu", Storage="_Phong", ThisKey="IdPhong", OtherKey="Id", IsForeignKey=true)]
		public Phong Phong
		{
			get
			{
				return this._Phong.Entity;
			}
			set
			{
				Phong previousValue = this._Phong.Entity;
				if (((previousValue != value) 
							|| (this._Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phong.Entity = null;
						previousValue.LichChieus.Remove(this);
					}
					this._Phong.Entity = value;
					if ((value != null))
					{
						value.LichChieus.Add(this);
						this._IdPhong = value.Id;
					}
					else
					{
						this._IdPhong = default(Nullable<int>);
					}
					this.SendPropertyChanged("Phong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Suatchieu_LichChieu", Storage="_Suatchieu", ThisKey="IdSC", OtherKey="IdSC", IsForeignKey=true)]
		public Suatchieu Suatchieu
		{
			get
			{
				return this._Suatchieu.Entity;
			}
			set
			{
				Suatchieu previousValue = this._Suatchieu.Entity;
				if (((previousValue != value) 
							|| (this._Suatchieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Suatchieu.Entity = null;
						previousValue.LichChieus.Remove(this);
					}
					this._Suatchieu.Entity = value;
					if ((value != null))
					{
						value.LichChieus.Add(this);
						this._IdSC = value.IdSC;
					}
					else
					{
						this._IdSC = default(Nullable<int>);
					}
					this.SendPropertyChanged("Suatchieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.LichChieu = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.LichChieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiGhe")]
	public partial class LoaiGhe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TenLoaiGhe;
		
		private double _GiaGhe;
		
		private EntitySet<Ghe> _Ghes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTenLoaiGheChanging(string value);
    partial void OnTenLoaiGheChanged();
    partial void OnGiaGheChanging(double value);
    partial void OnGiaGheChanged();
    #endregion
		
		public LoaiGhe()
		{
			this._Ghes = new EntitySet<Ghe>(new Action<Ghe>(this.attach_Ghes), new Action<Ghe>(this.detach_Ghes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiGhe", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TenLoaiGhe
		{
			get
			{
				return this._TenLoaiGhe;
			}
			set
			{
				if ((this._TenLoaiGhe != value))
				{
					this.OnTenLoaiGheChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiGhe = value;
					this.SendPropertyChanged("TenLoaiGhe");
					this.OnTenLoaiGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaGhe", DbType="Float NOT NULL")]
		public double GiaGhe
		{
			get
			{
				return this._GiaGhe;
			}
			set
			{
				if ((this._GiaGhe != value))
				{
					this.OnGiaGheChanging(value);
					this.SendPropertyChanging();
					this._GiaGhe = value;
					this.SendPropertyChanged("GiaGhe");
					this.OnGiaGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiGhe_Ghe", Storage="_Ghes", ThisKey="Id", OtherKey="Loai_id")]
		public EntitySet<Ghe> Ghes
		{
			get
			{
				return this._Ghes;
			}
			set
			{
				this._Ghes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ghes(Ghe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiGhe = this;
		}
		
		private void detach_Ghes(Ghe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiGhe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiPhim")]
	public partial class LoaiPhim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TenLoai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public LoaiPhim()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phim")]
	public partial class Phim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TenPhim;
		
		private string _AnhPhim;
		
		private int _ThoiLuong;
		
		private string _MoTa;
		
		private bool _TinhTrang;
		
		private string _IdLoaiPhim;
		
		private string _DienVien;
		
		private string _DaoDien;
		
		private System.DateTime _NgayCongChieu;
		
		private System.DateTime _NgayKetThuc;
		
		private string _NamPhatHanh;
		
		private string _ChatLuong;
		
		private EntitySet<BinhLuan> _BinhLuans;
		
		private EntitySet<Ve> _Ves;
		
		private EntitySet<LichChieu> _LichChieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTenPhimChanging(string value);
    partial void OnTenPhimChanged();
    partial void OnAnhPhimChanging(string value);
    partial void OnAnhPhimChanged();
    partial void OnThoiLuongChanging(int value);
    partial void OnThoiLuongChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnTinhTrangChanging(bool value);
    partial void OnTinhTrangChanged();
    partial void OnIdLoaiPhimChanging(string value);
    partial void OnIdLoaiPhimChanged();
    partial void OnDienVienChanging(string value);
    partial void OnDienVienChanged();
    partial void OnDaoDienChanging(string value);
    partial void OnDaoDienChanged();
    partial void OnNgayCongChieuChanging(System.DateTime value);
    partial void OnNgayCongChieuChanged();
    partial void OnNgayKetThucChanging(System.DateTime value);
    partial void OnNgayKetThucChanged();
    partial void OnNamPhatHanhChanging(string value);
    partial void OnNamPhatHanhChanged();
    partial void OnChatLuongChanging(string value);
    partial void OnChatLuongChanged();
    #endregion
		
		public Phim()
		{
			this._BinhLuans = new EntitySet<BinhLuan>(new Action<BinhLuan>(this.attach_BinhLuans), new Action<BinhLuan>(this.detach_BinhLuans));
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			this._LichChieus = new EntitySet<LichChieu>(new Action<LichChieu>(this.attach_LichChieus), new Action<LichChieu>(this.detach_LichChieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhim", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TenPhim
		{
			get
			{
				return this._TenPhim;
			}
			set
			{
				if ((this._TenPhim != value))
				{
					this.OnTenPhimChanging(value);
					this.SendPropertyChanging();
					this._TenPhim = value;
					this.SendPropertyChanged("TenPhim");
					this.OnTenPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhPhim", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string AnhPhim
		{
			get
			{
				return this._AnhPhim;
			}
			set
			{
				if ((this._AnhPhim != value))
				{
					this.OnAnhPhimChanging(value);
					this.SendPropertyChanging();
					this._AnhPhim = value;
					this.SendPropertyChanged("AnhPhim");
					this.OnAnhPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiLuong", DbType="Int NOT NULL")]
		public int ThoiLuong
		{
			get
			{
				return this._ThoiLuong;
			}
			set
			{
				if ((this._ThoiLuong != value))
				{
					this.OnThoiLuongChanging(value);
					this.SendPropertyChanging();
					this._ThoiLuong = value;
					this.SendPropertyChanged("ThoiLuong");
					this.OnThoiLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit NOT NULL")]
		public bool TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLoaiPhim", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string IdLoaiPhim
		{
			get
			{
				return this._IdLoaiPhim;
			}
			set
			{
				if ((this._IdLoaiPhim != value))
				{
					this.OnIdLoaiPhimChanging(value);
					this.SendPropertyChanging();
					this._IdLoaiPhim = value;
					this.SendPropertyChanged("IdLoaiPhim");
					this.OnIdLoaiPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienVien", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DienVien
		{
			get
			{
				return this._DienVien;
			}
			set
			{
				if ((this._DienVien != value))
				{
					this.OnDienVienChanging(value);
					this.SendPropertyChanging();
					this._DienVien = value;
					this.SendPropertyChanged("DienVien");
					this.OnDienVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaoDien", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DaoDien
		{
			get
			{
				return this._DaoDien;
			}
			set
			{
				if ((this._DaoDien != value))
				{
					this.OnDaoDienChanging(value);
					this.SendPropertyChanging();
					this._DaoDien = value;
					this.SendPropertyChanged("DaoDien");
					this.OnDaoDienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCongChieu", DbType="DateTime NOT NULL")]
		public System.DateTime NgayCongChieu
		{
			get
			{
				return this._NgayCongChieu;
			}
			set
			{
				if ((this._NgayCongChieu != value))
				{
					this.OnNgayCongChieuChanging(value);
					this.SendPropertyChanging();
					this._NgayCongChieu = value;
					this.SendPropertyChanged("NgayCongChieu");
					this.OnNgayCongChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="DateTime NOT NULL")]
		public System.DateTime NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this.OnNgayKetThucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThuc = value;
					this.SendPropertyChanged("NgayKetThuc");
					this.OnNgayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamPhatHanh", DbType="VarChar(50)")]
		public string NamPhatHanh
		{
			get
			{
				return this._NamPhatHanh;
			}
			set
			{
				if ((this._NamPhatHanh != value))
				{
					this.OnNamPhatHanhChanging(value);
					this.SendPropertyChanging();
					this._NamPhatHanh = value;
					this.SendPropertyChanged("NamPhatHanh");
					this.OnNamPhatHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChatLuong", DbType="VarChar(50)")]
		public string ChatLuong
		{
			get
			{
				return this._ChatLuong;
			}
			set
			{
				if ((this._ChatLuong != value))
				{
					this.OnChatLuongChanging(value);
					this.SendPropertyChanging();
					this._ChatLuong = value;
					this.SendPropertyChanged("ChatLuong");
					this.OnChatLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_BinhLuan", Storage="_BinhLuans", ThisKey="Id", OtherKey="IdPhim")]
		public EntitySet<BinhLuan> BinhLuans
		{
			get
			{
				return this._BinhLuans;
			}
			set
			{
				this._BinhLuans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_Ve", Storage="_Ves", ThisKey="Id", OtherKey="IdPhim")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_LichChieu", Storage="_LichChieus", ThisKey="Id", OtherKey="IdPhim")]
		public EntitySet<LichChieu> LichChieus
		{
			get
			{
				return this._LichChieus;
			}
			set
			{
				this._LichChieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.Phim = this;
		}
		
		private void detach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.Phim = null;
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.Phim = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.Phim = null;
		}
		
		private void attach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.Phim = this;
		}
		
		private void detach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.Phim = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phong")]
	public partial class Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TenPhong;
		
		private int _SoLuong;
		
		private int _SoluongHang;
		
		private int _Soluongghemoihang;
		
		private bool _TrinhTrang;
		
		private string _MoTa;
		
		private EntitySet<Ghe> _Ghes;
		
		private EntitySet<LichChieu> _LichChieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTenPhongChanging(string value);
    partial void OnTenPhongChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnSoluongHangChanging(int value);
    partial void OnSoluongHangChanged();
    partial void OnSoluongghemoihangChanging(int value);
    partial void OnSoluongghemoihangChanged();
    partial void OnTrinhTrangChanging(bool value);
    partial void OnTrinhTrangChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public Phong()
		{
			this._Ghes = new EntitySet<Ghe>(new Action<Ghe>(this.attach_Ghes), new Action<Ghe>(this.detach_Ghes));
			this._LichChieus = new EntitySet<LichChieu>(new Action<LichChieu>(this.attach_LichChieus), new Action<LichChieu>(this.detach_LichChieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhong", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TenPhong
		{
			get
			{
				return this._TenPhong;
			}
			set
			{
				if ((this._TenPhong != value))
				{
					this.OnTenPhongChanging(value);
					this.SendPropertyChanging();
					this._TenPhong = value;
					this.SendPropertyChanged("TenPhong");
					this.OnTenPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoluongHang", DbType="Int NOT NULL")]
		public int SoluongHang
		{
			get
			{
				return this._SoluongHang;
			}
			set
			{
				if ((this._SoluongHang != value))
				{
					this.OnSoluongHangChanging(value);
					this.SendPropertyChanging();
					this._SoluongHang = value;
					this.SendPropertyChanged("SoluongHang");
					this.OnSoluongHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluongghemoihang", DbType="Int NOT NULL")]
		public int Soluongghemoihang
		{
			get
			{
				return this._Soluongghemoihang;
			}
			set
			{
				if ((this._Soluongghemoihang != value))
				{
					this.OnSoluongghemoihangChanging(value);
					this.SendPropertyChanging();
					this._Soluongghemoihang = value;
					this.SendPropertyChanged("Soluongghemoihang");
					this.OnSoluongghemoihangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhTrang", DbType="Bit NOT NULL")]
		public bool TrinhTrang
		{
			get
			{
				return this._TrinhTrang;
			}
			set
			{
				if ((this._TrinhTrang != value))
				{
					this.OnTrinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TrinhTrang = value;
					this.SendPropertyChanged("TrinhTrang");
					this.OnTrinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_Ghe", Storage="_Ghes", ThisKey="Id", OtherKey="Id_phong")]
		public EntitySet<Ghe> Ghes
		{
			get
			{
				return this._Ghes;
			}
			set
			{
				this._Ghes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_LichChieu", Storage="_LichChieus", ThisKey="Id", OtherKey="IdPhong")]
		public EntitySet<LichChieu> LichChieus
		{
			get
			{
				return this._LichChieus;
			}
			set
			{
				this._LichChieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ghes(Ghe entity)
		{
			this.SendPropertyChanging();
			entity.Phong = this;
		}
		
		private void detach_Ghes(Ghe entity)
		{
			this.SendPropertyChanging();
			entity.Phong = null;
		}
		
		private void attach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.Phong = this;
		}
		
		private void detach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.Phong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Suatchieu")]
	public partial class Suatchieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdSC;
		
		private string _TenSuat;
		
		private System.Nullable<decimal> _phuthusc;
		
		private EntitySet<LichChieu> _LichChieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSCChanging(int value);
    partial void OnIdSCChanged();
    partial void OnTenSuatChanging(string value);
    partial void OnTenSuatChanged();
    partial void OnphuthuscChanging(System.Nullable<decimal> value);
    partial void OnphuthuscChanged();
    #endregion
		
		public Suatchieu()
		{
			this._LichChieus = new EntitySet<LichChieu>(new Action<LichChieu>(this.attach_LichChieus), new Action<LichChieu>(this.detach_LichChieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdSC
		{
			get
			{
				return this._IdSC;
			}
			set
			{
				if ((this._IdSC != value))
				{
					this.OnIdSCChanging(value);
					this.SendPropertyChanging();
					this._IdSC = value;
					this.SendPropertyChanged("IdSC");
					this.OnIdSCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSuat", DbType="NVarChar(20)")]
		public string TenSuat
		{
			get
			{
				return this._TenSuat;
			}
			set
			{
				if ((this._TenSuat != value))
				{
					this.OnTenSuatChanging(value);
					this.SendPropertyChanging();
					this._TenSuat = value;
					this.SendPropertyChanged("TenSuat");
					this.OnTenSuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phuthusc", DbType="Money")]
		public System.Nullable<decimal> phuthusc
		{
			get
			{
				return this._phuthusc;
			}
			set
			{
				if ((this._phuthusc != value))
				{
					this.OnphuthuscChanging(value);
					this.SendPropertyChanging();
					this._phuthusc = value;
					this.SendPropertyChanged("phuthusc");
					this.OnphuthuscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Suatchieu_LichChieu", Storage="_LichChieus", ThisKey="IdSC", OtherKey="IdSC")]
		public EntitySet<LichChieu> LichChieus
		{
			get
			{
				return this._LichChieus;
			}
			set
			{
				this._LichChieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.Suatchieu = this;
		}
		
		private void detach_LichChieus(LichChieu entity)
		{
			this.SendPropertyChanging();
			entity.Suatchieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private System.Nullable<System.DateTime> _NgayDangKy;
		
		private System.Nullable<bool> _TinhTrang;
		
		private string _PhanQuyen;
		
		private System.Nullable<int> _id_ThongTin;
		
		private EntitySet<BinhLuan> _BinhLuans;
		
		private EntitySet<Ve> _Ves;
		
		private EntitySet<DatVe> _DatVes;
		
		private EntityRef<ThongTin> _ThongTin;
		
		private EntityRef<Quyen> _Quyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnNgayDangKyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangKyChanged();
    partial void OnTinhTrangChanging(System.Nullable<bool> value);
    partial void OnTinhTrangChanged();
    partial void OnPhanQuyenChanging(string value);
    partial void OnPhanQuyenChanged();
    partial void Onid_ThongTinChanging(System.Nullable<int> value);
    partial void Onid_ThongTinChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._BinhLuans = new EntitySet<BinhLuan>(new Action<BinhLuan>(this.attach_BinhLuans), new Action<BinhLuan>(this.detach_BinhLuans));
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			this._DatVes = new EntitySet<DatVe>(new Action<DatVe>(this.attach_DatVes), new Action<DatVe>(this.detach_DatVes));
			this._ThongTin = default(EntityRef<ThongTin>);
			this._Quyen = default(EntityRef<Quyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(MAX)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(60)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangKy", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDangKy
		{
			get
			{
				return this._NgayDangKy;
			}
			set
			{
				if ((this._NgayDangKy != value))
				{
					this.OnNgayDangKyChanging(value);
					this.SendPropertyChanging();
					this._NgayDangKy = value;
					this.SendPropertyChanged("NgayDangKy");
					this.OnNgayDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit")]
		public System.Nullable<bool> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanQuyen", DbType="VarChar(50)")]
		public string PhanQuyen
		{
			get
			{
				return this._PhanQuyen;
			}
			set
			{
				if ((this._PhanQuyen != value))
				{
					if (this._Quyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._PhanQuyen = value;
					this.SendPropertyChanged("PhanQuyen");
					this.OnPhanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ThongTin", DbType="Int")]
		public System.Nullable<int> id_ThongTin
		{
			get
			{
				return this._id_ThongTin;
			}
			set
			{
				if ((this._id_ThongTin != value))
				{
					if (this._ThongTin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ThongTinChanging(value);
					this.SendPropertyChanging();
					this._id_ThongTin = value;
					this.SendPropertyChanged("id_ThongTin");
					this.Onid_ThongTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_BinhLuan", Storage="_BinhLuans", ThisKey="Id", OtherKey="IdTK")]
		public EntitySet<BinhLuan> BinhLuans
		{
			get
			{
				return this._BinhLuans;
			}
			set
			{
				this._BinhLuans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_Ve", Storage="_Ves", ThisKey="Id", OtherKey="IdTaiKhoan")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_DatVe", Storage="_DatVes", ThisKey="Id", OtherKey="IDTK")]
		public EntitySet<DatVe> DatVes
		{
			get
			{
				return this._DatVes;
			}
			set
			{
				this._DatVes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTin_TaiKhoan", Storage="_ThongTin", ThisKey="id_ThongTin", OtherKey="ThongTin_id", IsForeignKey=true)]
		public ThongTin ThongTin
		{
			get
			{
				return this._ThongTin.Entity;
			}
			set
			{
				ThongTin previousValue = this._ThongTin.Entity;
				if (((previousValue != value) 
							|| (this._ThongTin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThongTin.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._ThongTin.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._id_ThongTin = value.ThongTin_id;
					}
					else
					{
						this._id_ThongTin = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThongTin");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Quyen_TaiKhoan", Storage="_Quyen", ThisKey="PhanQuyen", OtherKey="Id", IsForeignKey=true)]
		public Quyen Quyen
		{
			get
			{
				return this._Quyen.Entity;
			}
			set
			{
				Quyen previousValue = this._Quyen.Entity;
				if (((previousValue != value) 
							|| (this._Quyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Quyen.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._Quyen.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._PhanQuyen = value.Id;
					}
					else
					{
						this._PhanQuyen = default(string);
					}
					this.SendPropertyChanged("Quyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
		
		private void attach_DatVes(DatVe entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_DatVes(DatVe entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTin")]
	public partial class ThongTin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ThongTin_id;
		
		private string _TenNguoiDung;
		
		private string _DiaChi;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _Email;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnThongTin_idChanging(int value);
    partial void OnThongTin_idChanged();
    partial void OnTenNguoiDungChanging(string value);
    partial void OnTenNguoiDungChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public ThongTin()
		{
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTin_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ThongTin_id
		{
			get
			{
				return this._ThongTin_id;
			}
			set
			{
				if ((this._ThongTin_id != value))
				{
					this.OnThongTin_idChanging(value);
					this.SendPropertyChanging();
					this._ThongTin_id = value;
					this.SendPropertyChanged("ThongTin_id");
					this.OnThongTin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiDung", DbType="NVarChar(MAX)")]
		public string TenNguoiDung
		{
			get
			{
				return this._TenNguoiDung;
			}
			set
			{
				if ((this._TenNguoiDung != value))
				{
					this.OnTenNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiDung = value;
					this.SendPropertyChanged("TenNguoiDung");
					this.OnTenNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="VarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(MAX)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTin_TaiKhoan", Storage="_TaiKhoans", ThisKey="ThongTin_id", OtherKey="id_ThongTin")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.ThongTin = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.ThongTin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Quyen")]
	public partial class Quyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _TenQuyen;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnTenQuyenChanging(string value);
    partial void OnTenQuyenChanged();
    #endregion
		
		public Quyen()
		{
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuyen", DbType="NVarChar(100)")]
		public string TenQuyen
		{
			get
			{
				return this._TenQuyen;
			}
			set
			{
				if ((this._TenQuyen != value))
				{
					this.OnTenQuyenChanging(value);
					this.SendPropertyChanging();
					this._TenQuyen = value;
					this.SendPropertyChanged("TenQuyen");
					this.OnTenQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Quyen_TaiKhoan", Storage="_TaiKhoans", ThisKey="Id", OtherKey="PhanQuyen")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.Quyen = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.Quyen = null;
		}
	}
}
#pragma warning restore 1591
