<?xml version="1.0" encoding="utf-8"?><Database Name="QUANLYRAPCHIEUPHIM" Class="QUANLYRAPCHIEUPHIMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-EKGAA51;Initial Catalog=QUANLYRAPCHIEUPHIM;User ID=sa" SettingsObjectName="DAL_BLL.Properties.Settings" SettingsPropertyName="QUANLYRAPCHIEUPHIMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BinhLuan" Member="BinhLuans">
    <Type Name="BinhLuan">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPhim" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdTK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DanhGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Phim_BinhLuan" Member="Phim" ThisKey="IdPhim" OtherKey="Id" Type="Phim" IsForeignKey="true" />
      <Association Name="TaiKhoan_BinhLuan" Member="TaiKhoan" ThisKey="IdTK" OtherKey="Id" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ve" Member="Ves">
    <Type Name="Ve">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdPhim" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdGhe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GiaVe" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdLC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdKM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Ghe_Ve" Member="Ghe" ThisKey="IdGhe" OtherKey="ghe_id" Type="Ghe" IsForeignKey="true" />
      <Association Name="LichChieu_Ve" Member="LichChieu" ThisKey="IdLC" OtherKey="Id" Type="LichChieu" IsForeignKey="true" />
      <Association Name="Phim_Ve" Member="Phim" ThisKey="IdPhim" OtherKey="Id" Type="Phim" IsForeignKey="true" />
      <Association Name="TaiKhoan_Ve" Member="TaiKhoan" ThisKey="IdTaiKhoan" OtherKey="Id" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CaChieu" Member="CaChieus">
    <Type Name="CaChieu">
      <Column Name="IdCC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="CaChieu_LichChieu" Member="LichChieus" ThisKey="IdCC" OtherKey="IdCC" Type="LichChieu" />
    </Type>
  </Table>
  <Table Name="dbo.DatVe" Member="DatVes">
    <Type Name="DatVe">
      <Column Name="IDDatVe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDTK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDve" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="TaiKhoan_DatVe" Member="TaiKhoan" ThisKey="IDTK" OtherKey="Id" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ghe" Member="Ghes">
    <Type Name="Ghe">
      <Column Name="ghe_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Loai_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TringTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Id_phong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenGhe" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HangGhe" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Ghe_Ve" Member="Ves" ThisKey="ghe_id" OtherKey="IdGhe" Type="Ve" />
      <Association Name="LoaiGhe_Ghe" Member="LoaiGhe" ThisKey="Loai_id" OtherKey="Id" Type="LoaiGhe" IsForeignKey="true" />
      <Association Name="Phong_Ghe" Member="Phong" ThisKey="Id_phong" OtherKey="Id" Type="Phong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LichChieu" Member="LichChieus">
    <Type Name="LichChieu">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayChieu" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Thu" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Phuthulc" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="IdPhim" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GioBD" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="GioKT" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="IdPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LichChieu_Ve" Member="Ves" ThisKey="Id" OtherKey="IdLC" Type="Ve" />
      <Association Name="CaChieu_LichChieu" Member="CaChieu" ThisKey="IdCC" OtherKey="IdCC" Type="CaChieu" IsForeignKey="true" />
      <Association Name="Phim_LichChieu" Member="Phim" ThisKey="IdPhim" OtherKey="Id" Type="Phim" IsForeignKey="true" />
      <Association Name="Phong_LichChieu" Member="Phong" ThisKey="IdPhong" OtherKey="Id" Type="Phong" IsForeignKey="true" />
      <Association Name="Suatchieu_LichChieu" Member="Suatchieu" ThisKey="IdSC" OtherKey="IdSC" Type="Suatchieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiGhe" Member="LoaiGhes">
    <Type Name="LoaiGhe">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiGhe" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="GiaGhe" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="LoaiGhe_Ghe" Member="Ghes" ThisKey="Id" OtherKey="Loai_id" Type="Ghe" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhim" Member="LoaiPhims">
    <Type Name="LoaiPhim">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Phim" Member="Phims">
    <Type Name="Phim">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhim" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AnhPhim" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IdLoaiPhim" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DienVien" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DaoDien" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NgayCongChieu" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NamPhatHanh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChatLuong" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Phim_BinhLuan" Member="BinhLuans" ThisKey="Id" OtherKey="IdPhim" Type="BinhLuan" />
      <Association Name="Phim_Ve" Member="Ves" ThisKey="Id" OtherKey="IdPhim" Type="Ve" />
      <Association Name="Phim_LichChieu" Member="LichChieus" ThisKey="Id" OtherKey="IdPhim" Type="LichChieu" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoluongHang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Soluongghemoihang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Phong_Ghe" Member="Ghes" ThisKey="Id" OtherKey="Id_phong" Type="Ghe" />
      <Association Name="Phong_LichChieu" Member="LichChieus" ThisKey="Id" OtherKey="IdPhong" Type="LichChieu" />
    </Type>
  </Table>
  <Table Name="dbo.Suatchieu" Member="Suatchieus">
    <Type Name="Suatchieu">
      <Column Name="IdSC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSuat" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="phuthusc" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Suatchieu_LichChieu" Member="LichChieus" ThisKey="IdSC" OtherKey="IdSC" Type="LichChieu" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="NgayDangKy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PhanQuyen" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="id_ThongTin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TaiKhoan_BinhLuan" Member="BinhLuans" ThisKey="Id" OtherKey="IdTK" Type="BinhLuan" />
      <Association Name="TaiKhoan_Ve" Member="Ves" ThisKey="Id" OtherKey="IdTaiKhoan" Type="Ve" />
      <Association Name="TaiKhoan_DatVe" Member="DatVes" ThisKey="Id" OtherKey="IDTK" Type="DatVe" />
      <Association Name="ThongTin_TaiKhoan" Member="ThongTin" ThisKey="id_ThongTin" OtherKey="ThongTin_id" Type="ThongTin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThongTin" Member="ThongTins">
    <Type Name="ThongTin">
      <Column Name="ThongTin_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNguoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="ThongTin_TaiKhoan" Member="TaiKhoans" ThisKey="ThongTin_id" OtherKey="id_ThongTin" Type="TaiKhoan" />
    </Type>
  </Table>
</Database>